// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// RunoobTbl is the golang structure for table runoob_tbl.
type RunoobTbl struct {
	RunoobId       uint        `orm:"runoob_id,primary" json:"runoobId"`       //
	RunoobTitle    string      `orm:"runoob_title"      json:"runoobTitle"`    //
	RunoobAuthor   string      `orm:"runoob_author"     json:"runoobAuthor"`   //
	SubmissionDate *gtime.Time `orm:"submission_date"   json:"submissionDate"` //
}

// User is the golang structure for table user.
type User struct {
	Id          uint        `orm:"id,primary"   json:"id"`          // 自增id
	GmtCreate   *gtime.Time `orm:"gmt_create"   json:"gmtCreate"`   // 创建时间
	GmtModify   *gtime.Time `orm:"gmt_modify"   json:"gmtModify"`   // 修改时间
	UserAccount string      `orm:"user_account" json:"userAccount"` // 用户账号
	UserPwd     string      `orm:"user_pwd"     json:"userPwd"`     // 用户密码
	Extend      string      `orm:"extend"       json:"extend"`      // 额外信息
}
